/**
 * 5-Test Validator for Draft Generator
 * Validates drafts against Colin's style rules
 */

// Anti-patterns regex patterns
const ANTI_PATTERNS = [
  { pattern: /Dear\s+(Sir|Madam|Sir\/Madam)/i, reason: 'Overly formal greeting' },
  { pattern: /calendly\.com|calendar link|book a time|schedule a call.*link/i, reason: 'Calendar links not allowed' },
  { pattern: /\$\d+|€\d+|£\d+.*day|day.*\$\d+|rate.*\$\d+|\d+.*euro.*day/i, reason: 'Rate disclosed in email' },
  { pattern: /I think this could be a good fit|maybe|possibly|might be/i, reason: 'Uncertainty language' },
  { pattern: /!!!|!!!!/, reason: 'Excessive exclamation marks' },
  { pattern: /AI|artificial intelligence|chatbot|generated by/i, reason: 'AI mention' },
  { pattern: /Yours (faithfully|sincerely)/i, reason: 'Overly formal sign-off' }
];

// Scenario word count ranges
const SCENARIO_RANGES = {
  'warm-handoff': { min: 80, max: 120 },
  'soft-close': { min: 40, max: 60 },
  'rate-discussion': { min: 50, max: 70 },
  'cv-received': { min: 50, max: 80 },
  'follow-up': { min: 40, max: 60 },
  'phone-request': { min: 30, max: 50 },
  'info-request': { min: 40, max: 70 }
};

/**
 * Run all 5 validation tests
 */
function run5TestValidation(draft, scenarioType) {
  const range = SCENARIO_RANGES[scenarioType] || { min: 50, max: 100 };
  
  const tests = {
    wordCount: testWordCount(draft, range),
    authorityPositioning: testAuthorityPositioning(draft),
    tone: testTone(draft),
    cta: testCTA(draft),
    antiPatterns: testAntiPatterns(draft)
  };
  
  const passed = Object.values(tests).every(t => t.pass);
  
  return { passed, tests };
}

/**
 * Test 1: Word count within scenario range
 */
function testWordCount(draft, range) {
  // Extract body only (remove signature)
  const bodyOnly = draft.replace(/\n\s*(Best|Regards|Thanks|Cheers),?\s*\n.*$/is, '').trim();
  const words = bodyOnly.split(/\s+/).filter(w => w.length > 0).length;
  
  return {
    value: words,
    min: range.min,
    max: range.max,
    pass: words >= range.min && words <= range.max,
    note: words < range.min ? `Too short (${words} words, min ${range.min})` : 
          words > range.max ? `Too long (${words} words, max ${range.max})` :
          `Perfect length (${words} words)`
  };
}

/**
 * Test 2: Authority positioning present
 */
function testAuthorityPositioning(draft) {
  const authorityMarkers = [
    /head(ing)? up.*European/i,
    /I recruit/i,
    /I'm (heading|leading)/i,
    /European division/i,
    /URecruit/i,
    /Harry has looped me in/i
  ];
  
  const found = authorityMarkers.some(pattern => pattern.test(draft));
  
  return {
    pass: found,
    note: found ? 'Authority positioning found' : 'Missing authority positioning (e.g., "I head up the European division")'
  };
}

/**
 * Test 3: Tone matches Colin's style
 */
function testTone(draft) {
  // Check for overly formal language
  const tooFormal = /Dear\s+\w+|Yours\s+(faithfully|sincerely)/i.test(draft);
  
  // Check for Colin's casual confidence markers
  const casualMarkers = [
    /Hi\s+\w+/i,
    /looks closely aligned/i,
    /could you kindly/i,
    /drop me/i,
    /give you a call/i,
    /looped me in/i
  ];
  const hasCasual = casualMarkers.some(p => p.test(draft));
  
  // Check for salesy/pushy language
  const tooSalesy = /amazing opportunity|perfect fit|don't miss out|limited time/i.test(draft);
  
  const pass = hasCasual && !tooFormal && !tooSalesy;
  
  let note = 'Tone appropriate';
  if (tooFormal) note = 'Too formal (use "Hi Name" not "Dear")';
  else if (tooSalesy) note = 'Too salesy/pushy';
  else if (!hasCasual) note = 'Missing Colin\'s casual tone markers';
  
  return { pass, note };
}

/**
 * Test 4: Clear CTA present
 */
function testCTA(draft) {
  const ctaPatterns = [
    /give you a call/i,
    /drop me (a )?(copy of your )?CV/i,
    /could you send/i,
    /worth a brief chat/i,
    /how about (a )?call/i,
    /let's (schedule|arrange)/i,
    /chat\?/i
  ];
  
  const hasCTA = ctaPatterns.some(p => p.test(draft));
  
  return {
    pass: hasCTA,
    note: hasCTA ? 'CTA present' : 'Missing clear call-to-action (ask for CV, suggest call, etc.)'
  };
}

/**
 * Test 5: No anti-patterns
 */
function testAntiPatterns(draft) {
  const violations = [];
  
  for (const { pattern, reason } of ANTI_PATTERNS) {
    if (pattern.test(draft)) {
      violations.push(reason);
    }
  }
  
  return {
    pass: violations.length === 0,
    violations,
    note: violations.length > 0 ? `Violations: ${violations.join(', ')}` : 'No anti-patterns detected'
  };
}

/**
 * Calculate confidence score based on test results
 */
function calculateConfidence(testResults) {
  let score = 100;
  
  // Word count off-target: -10 to -20
  if (!testResults.wordCount.pass) {
    const diff = Math.abs(testResults.wordCount.value - (testResults.wordCount.min + testResults.wordCount.max) / 2);
    score -= Math.min(20, diff);
  }
  
  // Missing authority: -15
  if (!testResults.authorityPositioning.pass) score -= 15;
  
  // Tone issues: -15
  if (!testResults.tone.pass) score -= 15;
  
  // Missing CTA: -20
  if (!testResults.cta.pass) score -= 20;
  
  // Anti-patterns: -10 each
  if (!testResults.antiPatterns.pass) {
    score -= testResults.antiPatterns.violations.length * 10;
  }
  
  return Math.max(0, Math.min(100, Math.round(score)));
}

module.exports = {
  run5TestValidation,
  calculateConfidence,
  SCENARIO_RANGES,
  ANTI_PATTERNS
};
